window.config = {
  ENV: '<ENV>',
  AUTH_BASE_URL: '<AUTH_BASE_URL>',
  AUTH_CLIENT_ID: '<AUTH_CLIENT_ID>',
  API_BASE_URL: '<API_BASE_URL>',
  LEADERBOARD_TYPE: '<LEADERBOARD_TYPE>',
  SLACK_CHANNEL_ID: '<SLACK_CHANNEL_ID>',
};
